-- Ejecutar en Supabase SQL Editor para habilitar proceso y control de tiempo por área.

-- 1) Columna proceso en tramites (opcional)
ALTER TABLE tramites
ADD COLUMN IF NOT EXISTS proceso text;

-- 2) Tabla tiempo_en_area (medición por área cuando el trámite tiene proceso)
CREATE TABLE IF NOT EXISTS tiempo_en_area (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tramite_id text NOT NULL REFERENCES tramites(id) ON DELETE CASCADE,
  area_nombre text NOT NULL,
  fecha_entrada timestamptz NOT NULL DEFAULT now(),
  fecha_salida timestamptz,
  proceso_id text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tiempo_en_area_tramite_id ON tiempo_en_area(tramite_id);
CREATE INDEX IF NOT EXISTS idx_tiempo_en_area_fecha_salida ON tiempo_en_area(tramite_id) WHERE fecha_salida IS NULL;

COMMENT ON TABLE tiempo_en_area IS 'Tiempo que un trámite permanece en cada área; solo se usa cuando el trámite tiene proceso asignado.';
