-- Notificaciones por tiempo transcurrido en trámites (50%, 70%, 100%).
-- Se envían a usuarios cuya área coincida con el área donde corre el tiempo del proceso.

-- Tabla de notificaciones (una fila por evento 50% / 70% / 100% por registro de tiempo_en_area)
CREATE TABLE IF NOT EXISTS notificaciones_tiempo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tiempo_en_area_id bigint NOT NULL REFERENCES tiempo_en_area(id) ON DELETE CASCADE,
  tramite_id text NOT NULL,
  tramite_titulo text NOT NULL,
  area_nombre text NOT NULL,
  porcentaje int NOT NULL CHECK (porcentaje IN (50, 70, 100)),
  mensaje text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notif_tiempo_una_por_porcentaje
  ON notificaciones_tiempo(tiempo_en_area_id, porcentaje);

CREATE INDEX IF NOT EXISTS idx_notif_tiempo_area ON notificaciones_tiempo(area_nombre);
CREATE INDEX IF NOT EXISTS idx_notif_tiempo_created ON notificaciones_tiempo(created_at DESC);

COMMENT ON TABLE notificaciones_tiempo IS 'Notificaciones cuando un trámite alcanza 50%, 70% o 100% del tiempo estimado en un área; se muestran a usuarios de esa área.';

-- Opcional: marcar como leída por usuario (evita duplicados en UI)
CREATE TABLE IF NOT EXISTS notificacion_leida (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notificacion_id bigint NOT NULL REFERENCES notificaciones_tiempo(id) ON DELETE CASCADE,
  usuario_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(notificacion_id, usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_notif_leida_usuario ON notificacion_leida(usuario_id);
