-- Ejecutar en Supabase SQL Editor para habilitar el historial de cargas (Cargar Obras).
-- Tabla usada al subir XML/Excel en "Cargar Obras"; si no existe, el procesamiento sigue pero no se guarda el registro.

CREATE TABLE IF NOT EXISTS historial_uploads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_archivo text NOT NULL,
  tipo_archivo text NOT NULL,
  fecha_subida timestamptz DEFAULT now(),
  registros_procesados int,
  registros_exitosos int,
  registros_fallidos int,
  usuario text,
  observaciones text
);

COMMENT ON TABLE historial_uploads IS 'Registro de cada archivo subido en Cargar Obras (XML/Excel).';
